//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("cancha", Schema = "dbo")]
    
    public partial class cancha
    {
    	[Key()]	
    	public int id_cancha { get; set; }
    	public int id_sede { get; set; }
    
        public virtual sede sede { get; set; }
    }
}
