//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("intento", Schema = "dbo")]
    
    public partial class intento
    {
    	[Key()]	
    	public int id_intento { get; set; }
    	public Nullable<int> id_partido_equipo { get; set; }
    
        public virtual partido_equipo partido_equipo { get; set; }
    }
}
