//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("jugador", Schema = "dbo")]
    
    public partial class jugador
    {
    	[Key()]	
    	public int id_jugador { get; set; }
    	public int id_persona_disciplina { get; set; }
    	public int id_equipo { get; set; }
    
        public virtual persona_disciplina persona_disciplina { get; set; }
    }
}
