//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("partido", Schema = "dbo")]
    
    public partial class partido
    {
        
        public partido()
        {
            this.partido_equipo = new HashSet<partido_equipo>();
            this.set = new HashSet<set>();
            this.tiempo = new HashSet<tiempo>();
        }
    
    	[Key()]	
    	public int id_partido { get; set; }
    	public int id_fixture { get; set; }
    
        public virtual fixture fixture { get; set; }
        
        public virtual ICollection<partido_equipo> partido_equipo { get; set; }
        
        public virtual ICollection<set> set { get; set; }
        
        public virtual ICollection<tiempo> tiempo { get; set; }
    }
}
