//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("perfil", Schema = "dbo")]
    
    public partial class perfil
    {
        
        public perfil()
        {
            this.usuario = new HashSet<usuario>();
        }
    
    	[Key()]	
    	public int id_perfil { get; set; }
    
        
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
