//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("persona_disciplina", Schema = "dbo")]
    
    public partial class persona_disciplina
    {
        
        public persona_disciplina()
        {
            this.jugador = new HashSet<jugador>();
        }
    
    	[Key()]	
    	public int id_persona_disciplina { get; set; }
    	public int id_persona { get; set; }
    	public int id_disciplina { get; set; }
    
        public virtual disciplina disciplina { get; set; }
        
        public virtual ICollection<jugador> jugador { get; set; }
        public virtual persona persona { get; set; }
    }
}
