//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("sede", Schema = "dbo")]
    
    public partial class sede
    {
        
        public sede()
        {
            this.cancha = new HashSet<cancha>();
        }
    
    	[Key()]	
    	public int id_sede { get; set; }
    	public int id_institucion { get; set; }
    
        
        public virtual ICollection<cancha> cancha { get; set; }
        public virtual institucion institucion { get; set; }
    }
}
