//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("sysdiagrams", Schema = "dbo")]
    
    public partial class sysdiagrams
    {
    	public string name { get; set; }
    	public int principal_id { get; set; }
    	[Key()]	
    	public int diagram_id { get; set; }
    	public Nullable<int> version { get; set; }
    	public byte[] definition { get; set; }
    }
}
