//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("torneo", Schema = "dbo")]
    
    public partial class torneo
    {
        
        public torneo()
        {
            this.torneo_disciplina = new HashSet<torneo_disciplina>();
        }
    
    	[Key()]	
    	public int id_torneo { get; set; }
    	public int id_institucion { get; set; }
    
        public virtual institucion institucion { get; set; }
        
        public virtual ICollection<torneo_disciplina> torneo_disciplina { get; set; }
    }
}
