//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("torneo_disciplina", Schema = "dbo")]
    
    public partial class torneo_disciplina
    {
        
        public torneo_disciplina()
        {
            this.torneo_disciplina_categoria = new HashSet<torneo_disciplina_categoria>();
        }
    
    	[Key()]	
    	public int id_torneo_disciplina { get; set; }
    	public Nullable<int> id_torneo { get; set; }
    	public Nullable<int> id_institucion_disciplina { get; set; }
    
        public virtual institucion_disciplina institucion_disciplina { get; set; }
        public virtual torneo torneo { get; set; }
        
        public virtual ICollection<torneo_disciplina_categoria> torneo_disciplina_categoria { get; set; }
    }
}
