//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("torneo_disciplina_categoria", Schema = "dbo")]
    
    public partial class torneo_disciplina_categoria
    {
        
        public torneo_disciplina_categoria()
        {
            this.equipo = new HashSet<equipo>();
            this.fixture = new HashSet<fixture>();
            this.ranking = new HashSet<ranking>();
        }
    
    	[Key()]	
    	public int id_torneo_disciplina_categoria { get; set; }
    	public int id_torneo_disciplina { get; set; }
    	public int id_institucion_disciplina_categoria { get; set; }
    
        
        public virtual ICollection<equipo> equipo { get; set; }
        
        public virtual ICollection<fixture> fixture { get; set; }
        public virtual institucion_disciplina_categoria institucion_disciplina_categoria { get; set; }
        
        public virtual ICollection<ranking> ranking { get; set; }
        public virtual torneo_disciplina torneo_disciplina { get; set; }
    }
}
