//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("usuario", Schema = "dbo")]
    
    public partial class usuario
    {
        
        public usuario()
        {
            this.perfil = new HashSet<perfil>();
        }
    
    	[Key()]	
    	public int id_usario { get; set; }
    	public int id_persona { get; set; }
    	public Nullable<int> id_institucion { get; set; }
    
        public virtual institucion institucion { get; set; }
        public virtual persona persona { get; set; }
        
        public virtual ICollection<perfil> perfil { get; set; }
    }
}
