//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.MAKEUP.Datos.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Prod.MAKEUP.Datos.Modelo;
    
    public partial class ArquetipoContext : DbContext
    {
        public ArquetipoContext()
            : base("name=ArquetipoContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<cancha> cancha { get; set; }
        public virtual DbSet<disciplina> disciplina { get; set; }
        public virtual DbSet<equipo> equipo { get; set; }
        public virtual DbSet<fixture> fixture { get; set; }
        public virtual DbSet<institucion> institucion { get; set; }
        public virtual DbSet<institucion_disciplina> institucion_disciplina { get; set; }
        public virtual DbSet<institucion_disciplina_categoria> institucion_disciplina_categoria { get; set; }
        public virtual DbSet<intento> intento { get; set; }
        public virtual DbSet<jugador> jugador { get; set; }
        public virtual DbSet<partido> partido { get; set; }
        public virtual DbSet<partido_equipo> partido_equipo { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<persona_disciplina> persona_disciplina { get; set; }
        public virtual DbSet<ranking> ranking { get; set; }
        public virtual DbSet<sede> sede { get; set; }
        public virtual DbSet<set> set { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tiempo> tiempo { get; set; }
        public virtual DbSet<torneo> torneo { get; set; }
        public virtual DbSet<torneo_disciplina> torneo_disciplina { get; set; }
        public virtual DbSet<torneo_disciplina_categoria> torneo_disciplina_categoria { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
