//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.BUPER.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CONFIGURACION_CAMPOS
    {
        public int id_configuracion_campos { get; set; }
        public string nombre_campo { get; set; }
        public int indice_inicio { get; set; }
        public int indice_fin { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public string usuario_modificacion { get; set; }
    }
}
