//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.BUPER.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_CODIGO_TUPA
    {
        public int id_codigo { get; set; }
        public int id_tupa { get; set; }
        public string estado { get; set; }
    
        public virtual MAE_CODIGO MAE_CODIGO { get; set; }
    }
}
