//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.BUPER.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_ARCHIVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAT_ARCHIVO()
        {
            this.DAT_REGISTRO = new HashSet<DAT_REGISTRO>();
        }
    
        public int id_archivo { get; set; }
        public string nom_archivo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string trama_ultima { get; set; }
        public Nullable<decimal> total_recaudado { get; set; }
        public Nullable<int> numero_pagos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_REGISTRO> DAT_REGISTRO { get; set; }
    }
}
