//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.BUPER.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_DEPENDENCIA
    {
        public int CODIGO_DEPENDENCIA { get; set; }
        public string DEPENDENCIA { get; set; }
        public string PISO { get; set; }
        public string SIGLAS { get; set; }
        public Nullable<System.DateTime> AUDIT_MOD { get; set; }
        public Nullable<System.DateTime> AUDIT_CREA { get; set; }
        public string CONDICION { get; set; }
        public string DIRECTO { get; set; }
        public string ANEXO { get; set; }
        public string SECCION { get; set; }
        public string CENTRAL { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string EQUIVALENCIA { get; set; }
        public Nullable<int> PRIORIDAD { get; set; }
        public Nullable<int> TIPO_DEPENDENCIA { get; set; }
        public Nullable<int> CODDEP_PUB { get; set; }
        public string PUBLICADO_WEB { get; set; }
        public string USUARIO_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<int> CODDEP_RESPONSABLE { get; set; }
        public Nullable<int> ID_TIPO_DEPENDENCIA { get; set; }
        public string PUBLICADO_EXTRANET { get; set; }
    }
}
