//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.BUPER.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_CODIGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAE_CODIGO()
        {
            this.DAT_CODIGO_TUPA = new HashSet<DAT_CODIGO_TUPA>();
            this.DAT_REGISTRO = new HashSet<DAT_REGISTRO>();
        }
    
        public int id_codigo { get; set; }
        public string codigo_tributo { get; set; }
        public string nom_codigo { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_CODIGO_TUPA> DAT_CODIGO_TUPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_REGISTRO> DAT_REGISTRO { get; set; }
    }
}
