//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.BUPER.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public int id_persona { get; set; }
        public string nombres { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string dni { get; set; }
        public int id_genero { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
