//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.BUPER.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ENUMERADO
    {
        public int id_tipo_enumerado { get; set; }
        public string descripcion { get; set; }
        public bool es_eliminado { get; set; }
        public bool genera_codigo_fuente { get; set; }
    }
}
