//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.BUPER.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUPA
    {
        public int ID_TUPA { get; set; }
        public Nullable<int> ID_CLASE_TUPA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> NUMERO_DIAS { get; set; }
        public Nullable<decimal> UIT { get; set; }
        public Nullable<int> CODIGO_DEPENDENCIA { get; set; }
        public Nullable<int> ESTADO_TUPA { get; set; }
        public Nullable<int> TIPO_APROBACION { get; set; }
        public Nullable<int> NUMERO_TUPA { get; set; }
        public Nullable<int> FLAG_CAMBIO { get; set; }
        public Nullable<int> ID_SECTOR { get; set; }
        public Nullable<int> ID_TIPO_SILENCIO { get; set; }
    }
}
